### ISSUE TITLE
Configuration through yml config file

### ISSUE THREAD

**Issue by umpirsky** [umpirsky/centipede#13]
centipede.yml:

```
rules:
    - url: http://example.com/foo
      status: 200
      text: Foo
    - url: http://example.com/bar
      status: 202
      text: Bar
```
